checksumBehavior: update

nodeLinker: node-modules

npmRegistryServer: "https://npm.coinweb.io/"

yarnPath: .yarn/releases/yarn-4.1.1.cjs

injectEnvironmentFiles:
  - ".env.yarn"
  - ".env.yarn.devnet?"
